# Generated by Django 2.1.7 on 2019-03-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=350, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
