# Generated by Django 2.1.7 on 2019-03-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=350, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comportamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motivacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem_perfil', models.ImageField(upload_to='media/img')),
                ('padrao_comportamento', models.CharField(max_length=450)),
                ('comportamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.Comportamento')),
                ('motivacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.Motivacao')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
                ('avaliacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.Avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='PontoDaMelhoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontoForte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
                ('perfil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.Perfil')),
                ('pergunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.Pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='ponto_da_melhoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.PontoDaMelhoria'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ponto_forte_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.PontoForte'),
        ),
    ]
