# Generated by Django 2.1.7 on 2019-03-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
                ('avaliacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.Avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350, unique=True)),
                ('pergunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_perfil.Pergunta')),
            ],
        ),
    ]
